/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function LockModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/lock.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["defaultMaterial.008Action.001"].reset().fadeIn(1).play();
    actions["defaultMaterial.011Action.001"].reset().fadeIn(1).play();
    actions["defaultMaterial.014Action.001"].reset().fadeIn(1).play();
    actions["defaultMaterial.017Action.001"].reset().fadeIn(1).play();
    actions["defaultMaterial.002Action.001"].reset().fadeIn(1).play();

    return () => {
      actions["defaultMaterial.008Action.001"]?.reset().fadeOut(1);
      actions["defaultMaterial.011Action.001"]?.reset().fadeOut(1);
      actions["defaultMaterial.014Action.001"]?.reset().fadeOut(1);
      actions["defaultMaterial.017Action.001"]?.reset().fadeOut(1);
      actions["defaultMaterial.002Action.001"]?.reset().fadeOut(1);
    };
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="Collada_visual_scene_group"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Body_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                name="defaultMaterial"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial.geometry}
                material={materials.DefaultMaterial}
              />
            </group>
            <group
              name="Combinations_low"
              position={[6.593, 8.368, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <group name="defaultMaterial005" />
              <mesh
                name="defaultMaterial006"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial006.geometry}
                material={materials.DefaultMaterial}
              />
              <mesh
                name="defaultMaterial007"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial007.geometry}
                material={materials.DefaultMaterial}
              />
              <mesh
                name="defaultMaterial008"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial008.geometry}
                material={materials.DefaultMaterial}
              />
              <mesh
                name="defaultMaterial009"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial009.geometry}
                material={materials.DefaultMaterial}
              />
              <mesh
                name="defaultMaterial010"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial010.geometry}
                material={materials.DefaultMaterial}
              />
              <mesh
                name="defaultMaterial011"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial011.geometry}
                material={materials.DefaultMaterial}
              />
              <mesh
                name="defaultMaterial012"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial012.geometry}
                material={materials.DefaultMaterial}
              />
              <mesh
                name="defaultMaterial013"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial013.geometry}
                material={materials.DefaultMaterial}
              />
              <mesh
                name="defaultMaterial014"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial014.geometry}
                material={materials.DefaultMaterial}
              />
              <mesh
                name="defaultMaterial015"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial015.geometry}
                material={materials.DefaultMaterial}
              />
              <mesh
                name="defaultMaterial016"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial016.geometry}
                material={materials.DefaultMaterial}
              />
              <mesh
                name="defaultMaterial017"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial017.geometry}
                material={materials.DefaultMaterial}
              />
            </group>
            <group name="Glass_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                name="defaultMaterial004"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial004.geometry}
                material={materials.DefaultMaterial}
              />
            </group>
            <group
              name="Lock_low"
              position={[-6.177, 16.484, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="defaultMaterial003"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial003.geometry}
                material={materials.DefaultMaterial}
              />
            </group>
            <group
              name="Rod_low"
              position={[6.605, 6.417, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={31.475}
            >
              <mesh
                name="defaultMaterial002"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial002.geometry}
                material={materials.DefaultMaterial}
              />
            </group>
            <group
              name="RodHandle_low"
              position={[6.605, 6.417, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={31.475}
            >
              <mesh
                name="defaultMaterial001"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial001.geometry}
                material={materials.DefaultMaterial}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/lock.glb");
